Feat(Menu): Implementação da feature de Cadastro e Manutenção de itens no Menu
BrenoCinUfpe/ESS-E-commerce-Frontend pull request #14
Opened 2024-07-26 04:53 UTC by annecollier

2024-07-26 20:39 UTC, BrenoRev requested changes

2024-07-26 20:39 UTC, BrenoRev commented on src/app/layout.tsx
> -  title: "E-Commerce Sapatos",
Você removeu o nome certo da página

2024-07-26 20:39 UTC, BrenoRev commented on src/app/layout.tsx
> -  description: "Projeto da disciplina de Engenharia de Software (CIn - UFPE)",
Você removeu o nome certo da página

2024-07-26 20:39 UTC, BrenoRev commented on src/components/navbar.tsx
> +                  <Link href={`${searchString.length>0 ? `/product?searchString=${searchString}` : `/` }`}>
não seria /admin/product?

2024-07-27 01:37 UTC, CaioRSV commented on src/app/page.tsx
> +    let tempCategoria = param.get("categoria");
temps inutilizados no useEffect. No futuro, alterar lógica para utilizar as variáveis como `searchFilter` e etc para ditar os fetchs específicos, e utilizar os params apenas para popular elas caso necessário ao carregar a página de primeira

2024-07-27 01:39 UTC, CaioRSV commented on src/app/admin/product/page.tsx
> +    console.log({productData, updatedData: newData});
Remover `console.logs`

2024-07-27 03:01 UTC, annecollier commented on src/components/navbar.tsx
> +                  <Link href={`${searchString.length>0 ? `/product?searchString=${searchString}` : `/` }`}>
Esse search ocorre pro cliente mesmo

2024-07-27 17:27 UTC, CaioRSV approved these changes
Mudanças relacionadas às partes especificadas das features executadas

2024-07-28 04:55 UTC, merged