feat: add delivery time and order notification
BrenoCinUfpe/ESS-E-commerce-Frontend pull request #15
Opened 2024-07-27 05:46 UTC by amandaarruda

2024-07-27 05:47 UTC, amandaarruda commented
still missing cypress tests

2024-07-27 18:02 UTC, CaioRSV requested changes
Ajustes visuais requisitados

2024-07-27 18:02 UTC, CaioRSV commented on src/app/carrinho/page.tsx
> +                                    <p className={`cursor-pointer font-abeezee text-3xl flex-1 flex justify-center items-center rounded-full`} onClick={()=>{changeQuantity(item.productId, item.quanti
Botão de adicionar e elemento que mostra quantidade de item duplicados. Se deve ter apenas um de cada.

2024-07-27 20:39 UTC, amandaarruda commented on src/app/carrinho/page.tsx
> +                                    <p className={`cursor-pointer font-abeezee text-3xl flex-1 flex justify-center items-center rounded-full`} onClick={()=>{changeQuantity(item.productId, item.quanti
não sei pq ficou assim :P acho que repeti sem querer

2024-07-27 20:39 UTC, amandaarruda commented on src/app/carrinho/page.tsx
> +                  <div className="w-full h-full">
adicionado!

2024-07-27 20:47 UTC, amandaarruda commented
fixed bugs

2024-07-28 01:08 UTC, CaioRSV approved these changes

2024-07-28 04:55 UTC, merged